USE codingtest;

CREATE TABLE ANIMAL_INS(
	ANIMAL_ID VARCHAR(50) NOT NULL,
    ANIMAL_TYPE	VARCHAR(50) NOT NULL,
    `DATETIME` DATETIME NOT NULL,
    INTAKE_CONDITION VARCHAR(50) NOT NULL,
    `NAME` VARCHAR(50),
    SEX_UPON_INTAKE	VARCHAR(50) NOT NULL
);

DESC ANIMAL_INS;

CREATE TABLE ANIMAL_OUTS(
	ANIMAL_ID VARCHAR(50) NOT NULL,
    ANIMAL_TYPE	VARCHAR(50) NOT NULL,
    `DATETIME` DATETIME NOT NULL,
    `NAME` VARCHAR(50),
    SEX_UPON_OUTCOME VARCHAR(50) NOT NULL
);

DESC ANIMAL_OUTS;

INSERT INTO ANIMAL_INS (ANIMAL_ID, ANIMAL_TYPE, `DATETIME`, INTAKE_CONDITION, `NAME`, SEX_UPON_INTAKE)
VALUES
	('A352713', 'Cat', '2017-04-13 16:29:00', 'Normal', 'Gia', 'Spayed Female'),
    ('A350375', 'Cat', '2017-03-06 15:01:00', 'Normal', 'Meo', 'Neutered Male');

SELECT * FROM ANIMAL_INS;

INSERT INTO ANIMAL_OUTS (ANIMAL_ID, ANIMAL_TYPE, `DATETIME`, `NAME`, SEX_UPON_OUTCOME)    
VALUES
	('A349733', 'Dog', '2017-09-27 19:09:00', 'Allie', 'Spayed Female'),
    ('A352713', 'Cat', '2017-04-25 12:25:00', 'Gia', 'Spayed Female'),
    ('A349990', 'Cat', '2018-02-02 14:18:00', 'Spice', 'Spayed Female');
    
SELECT * FROM ANIMAL_OUTS;

SELECT OUTS.ANIMAL_ID, OUTS.`NAME` FROM ANIMAL_OUTS AS OUTS
LEFT JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.`DATETIME` IS NULL
ORDER BY OUTS.ANIMAL_ID;
    
