USE codingtest;

INSERT INTO ANIMAL_INS (ANIMAL_ID, ANIMAL_TYPE, `DATETIME`, INTAKE_CONDITION, `NAME`, SEX_UPON_INTAKE)
VALUES
	('A350276', 'Cat', '2017-08-13 13:50:00', 'Normal', 'Jewel', 'Spayed Female'),
    ('A381217', 'Dog', '2017-07-08 09:41:00', 'Sick', 'Cherokee', 'Neutered Male');
    
SELECT * FROM ANIMAL_INS;

INSERT INTO ANIMAL_OUTS (ANIMAL_ID, ANIMAL_TYPE, `DATETIME`, `NAME`, SEX_UPON_OUTCOME)    
VALUES
	('A350276', 'Cat', '2018-01-28 17:51:00', 'Jewel', 'Spayed Female'),
    ('A381217', 'Dog', '2017-06-09 18:51:00', 'Cherokee', 'Neutered Male');
    
SELECT * FROM ANIMAL_OUTS;

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.`NAME` FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.`DATETIME` > ANIMAL_OUTS.`DATETIME`
ORDER BY ANIMAL_INS.`DATETIME`;